### ISSUE TITLE
[Model] OOM-B099

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2543] opened 2023-02-24 19:25 UTC
Actually this is a skin 
Author = Jefe

Model author = EvilEngine
Droids VP Author = Sergeant Todd
JunkVoice VP Author = Slyrr

Source=Readme

Contents are a duplicate of https://unrealarchive.org/models/unreal-tournament-2004/O/oom-b099_be878bce.html

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/O/oom-b099_8669c024.html
Hash: 8669c0244c2cc8a22ee29bbdb70f1cbc4c45c9e3
Current name: OOM-B099

**Comment by shrimpza** [comment] 2023-08-31 01:47
Duplicate of #2542

**Closed by shrimpza** 2023-08-31 01:47 UTC
