### ISSUE TITLE
[Map] DM-TrainingDay

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1361] opened 2022-05-23 11:12 UTC
Evidently not a DM map with only 1 Player and no bot support? 

The Also In link goes to the Not Found page.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/T/dm-trainingday_4a2453e9.html
Hash: 4a2453e9699277f6f79c0dbf7f778a33aab5804f
Current name: DM-TrainingDay

**Comment by NeonKnightOA** [comment] 2022-05-23 15:32
This is actually a duplicate of a previous map which I forgot to delete: DM-JT-TrainingDay. Dumb me!

**Closed** 2022-05-24 01:06 UTC
